### ISSUE TITLE
Make new release and update wiki

### ISSUE THREAD

**Issue by x29a** [Seeed-Studio/Seeed_Arduino_DopplerRadar#11]
hi @Pillar1989,

thank you for keeping this project active by merging changes and additions!

when would be a good time for a new release?

also, do you know anybody that could update the wiki to reflect the changes and incorporate the new release? i opened [this PR](https://github.com/Seeed-Studio/wiki-documents/pull/8) which did not get any attention yet.

**Comment by Pillar1989** [comment]
@lakshanthad  can u help me do this work?

**Comment by lakshanthad** [comment]
Hello @x29a,

Thank you for your contributions. We really appreciate it!

I have made the new release. I will also arrange to change the wiki to reflect the changes.

**Comment by lakshanthad** [comment]
@x29a ,

Have you properly tested the hardware with the latest changes in the code so that we can update the wiki?

**Comment by lakshanthad** [comment]
@x29a ,

Have you properly tested the hardware with the latest changes in the code so that we can update the wiki?

**Comment by x29a** [comment]
@lakshanthad thanks for the new release. 

I have tested the rev 1.0 BGT24LTR11 board for multiple days in target detection mode and read the speed. I did not test the I/Q mode, but there were no changes there.

If there is anything else you want me to test, i can do that easily and happily!
