### ISSUE TITLE
Calling getSpeed() with delays of 300 ms or larger between readings causes lag and data corruption

### ISSUE THREAD

**Issue by adriaanb** [Seeed-Studio/Seeed_Arduino_DopplerRadar#5]
According to the [specifications](https://wiki.seeedstudio.com/Grove-Doppler-Radar/#specification) of the sensor, the sensor reading is updated every 300 ms. 

Using delays of less than 300 ms between calls of getSpeed() therefore yields redundant readings. Using a delay of 300 ms or larger to ensure non-redundant readings will however lead to increasing lag and corruption in the data returned. This might also be the case for some lower values, 200 ms is confirmed to work. Calling the function too fast in succession however will cause issue #3. 

This behavior can be reproduced using the [BGT24LTR11_DETECTION_TARGET.ino](https://github.com/Seeed-Studio/Seeed_Arduino_DopplerRadar/blob/master/examples/BGT24LTR11_DETECTION_TARGET/BGT24LTR11_DETECTION_TARGET.ino) example code. I tested it on an Arduino Nano 33 IoT.

**Comment by Pillar1989** [comment]
@adriaanb  I saw a series of questions from you. Is it the same question?

**Comment by adriaanb** [comment]
@Pillar1989 No, they are three different issues. The behavior of issues #3 and #4 are similar, issue #5 is different.

**Comment by x29a** [comment]
@adriaanb if you need to rely on values only to be received once, i would not call `getSpeed()` and such but just read from the module since it will send its updated values on its own each 300ms. 

Syncing the two devices via delays is near impossible IMHO.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by x29a** [comment]
I think this can be closed as different solutions were proposed:
* dont try to sync the two devices via sleep but wait for device to send info periodically
* use `getInfo()` in newest version (see https://github.com/Seeed-Studio/Seeed_Arduino_DopplerRadar/pull/13)

**Comment by Lesords** [comment]
Thank you for your suggestion, I will close this issue.
